language: ruby
rvm: 2.0.0
notifications:
  email: false
bundler_args: --binstubs
env:
  global:
    - GIT_COMMITTER_NAME=1000ch
    - GIT_COMMITTER_EMAIL=orz1000ch@gmail.com
    - GIT_AUTHOR_NAME=1000ch
    - GIT_AUTHOR_EMAIL=orz1000ch@gmail.com
    - secure: hEJhvxnzAOSTS9aQnTAdJ9bPROus4BSF7Npw5WEfVq9awbLSt9OGfv04vVnbafsoEp6PmLntfvHp+d/7gEM2fvNmGMJm1wn6T1tGt4GhfBqac6IulvmfZHGT0h6522a2RhWa1qHct2yL1uHB+mtfQwkn18RO5G42CyEVK3fHEo4=
before_script:
    - git clone --quiet https://github.com/1000ch/middleman-playground.git build
    - pushd build
    - git checkout -b gh-pages
    - npm install
    - ./node_modules/grunt-cli/bin/grunt
    - popd
script:
    - bundle exec middleman build
after_success:
    - cd build
    - git add -A
    - git commit -m 'Update'
    - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/1000ch/middleman-playground.git gh-pages 2> /dev/null'